### ISSUE TITLE
Video isn't rendered.

### ISSUE THREAD

**Issue by ITotalJustice** [v0idv0id/MPVideoCube#1]
Hi, thanks for the tutorial, it was quite helpful :smile: 

However i noticed a mistake in the code. You have `ADVANCED_CONTROL` enabled in the params, this means that you have to call `mpv_render_context_update()` after each call is made to the callback set with `mpv_render_context_set_update_callback()`. Or you can disable advanced control and the code will work just fine.

**Comment by v0idv0id** [comment]
Yes, you are right that is "wrong" according to "mpv/render.h" - the strange thing is: on my system it works without any problem if the settings are "1" (enabled). Down the rabbit hole ;-)

**Comment by v0idv0id** [comment]
Updated the code to use the advanced render path method with the callback - now its fine. Render FPS is now independent of video FPS. Did some additional cleanup.
